### ISSUE TITLE
The Arrow Keys make the User Unable to Review/Analyze the Game

### ISSUE THREAD

**Issue by sapere-dev** [FanaroEngineering/ogs_kbd_nav#13]
I think your code is programmatically pressing <kbd>Back to game</kbd> when you strike the <kbd>a</kbd> key as well as the left arrow. This is annoying if trying to use the keyboard nav to analyse and review a game.

**Comment by sapere-dev** [comment]
One suggestion might be to disable the 'return to game' behaviour if ctrl-B hasn't been pressed?

**Comment by psygo** [comment]
> I think your code is programmatically pressing <kbd>Back to game</kbd> when you strike the <kbd>a</kbd> key as well as the left arrow.

Yes, that's exactly what I'm programmatically doing, mostly because I had not found a way of disabling the return to game behavior. How I exactly do I disable it?

**Comment by sapere-dev** [comment]
> Yes, that's exactly what I'm programmatically doing, mostly because I had not found a way of disabling the return to game behavior. How I exactly do I disable it?

What if you only programmatically press the button whenever the user presses the left key? Or you could give up supporting the arrow keys  (or offer an option to switch them off), since they already control the game tree navigation. WASD should be sufficient to move the selector, no?

**Comment by psygo** [comment]
> WASD should be sufficient to move the selector, no?

Yeah, they are sufficient, but they feel much less ergonomic and natural to me. I would rather have both interfaces supported.

I kinda let it be for now because I was still hoping to find a way of disabling that "return to game" stuff through the `global_goban` global variable. Maybe you can try to find a way of disabling that mode there? Maybe there isn't a way?
I'm probably gonna have to end up asking @anoek in the end.
